{{- if .Values.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ghidra-authpanel.fullname" . }}-env
  labels:
    {{- include "ghidra-authpanel.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | toString | quote }}
  {{- end }}
{{- end }}
