{{- if and .Values.panel.enabled (not .Values.panel.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ghidra-server.jaasSecretName" . }}
  labels:
    {{- include "ghidra-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  jaas.conf: |
    auth {
        re.mkw.srejaas.PanelLoginModule REQUIRED
            JDBC={{ .Values.panel.jdbc | quote }};
    };
{{- end }}
